//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonPayment
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public int CreditCardNumber { get; set; }
        public string NameOnCard { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int CVV { get; set; }
        public System.DateTime DateEntered { get; set; }
    
        public virtual Receiver Receiver { get; set; }
    }
}
