//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhishingDatabaseEntities : DbContext
    {
        public PhishingDatabaseEntities()
            : base("name=PhishingDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AmazonLogin> AmazonLogin { get; set; }
        public virtual DbSet<AmazonPayment> AmazonPayment { get; set; }
        public virtual DbSet<InstagramLogin> InstagramLogin { get; set; }
        public virtual DbSet<Receiver> Receiver { get; set; }
        public virtual DbSet<TwitterLogin> TwitterLogin { get; set; }
    }
}
