//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver
    {
        public int ID { get; set; }
    
        public virtual AmazonLogin AmazonLogin { get; set; }
        public virtual AmazonPayment AmazonPayment { get; set; }
        public virtual InstagramLogin InstagramLogin { get; set; }
        public virtual TwitterLogin TwitterLogin { get; set; }
    }
}
